version: "3.1"

services:
  pg_db:
    restart: always
    image: postgres
    container_name: pg_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=test_db
    ports:
      - "5555:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
      - pg-network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pg_client
    environment:
      - PGADMIN_DEFAULT_EMAIL=test@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret
    ports:
      - 80:80
    depends_on:
      - "pg_db"
    networks:
      - pg-network

networks:
  pg-network:
    driver: bridge
